In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv("../data/raw/stockerbot-export1.csv")

In [3]:
label_df = pd.read_csv("../data/labeled/tweet_sentiment.csv")

In [4]:
raw_df.head()

,id,text,timestamp,source,symbols,company_names,url,verified
0,1.0197E+18,VIDEO: “I was in my office. I was minding my o...,Wed Jul 18 21:33:26 +0000 2018,GoldmanSachs,GS,The Goldman Sachs,https://twitter.com/i/web/status/1019696670777...,TRUE
1,1.01971E+18,The price of lumber $LB_F is down 22% since hi...,Wed Jul 18 22:22:47 +0000 2018,StockTwits,M,Macy's,https://twitter.com/i/web/status/1019709091038...,TRUE
2,1.01971E+18,Who says the American Dream is dead? https://t...,Wed Jul 18 22:32:01 +0000 2018,TheStreet,AIG,American,https://buff.ly/2L3kmc4,TRUE
3,1.01972E+18,Barry Silbert is extremely optimistic on bitco...,Wed Jul 18 22:52:52 +0000 2018,MarketWatch,BTC,Bitcoin,https://twitter.com/i/web/status/1019716662587...,TRUE
4,1.01972E+18,How satellites avoid attacks and space junk wh...,Wed Jul 18 23:00:01 +0000 2018,Forbes,ORCL,Oracle,http://on.forbes.com/6013DqDDU,TRUE

In [5]:
label_df.head()

                                      cleaned_tweets  sentiment
0  video offic mind busi david solomon tell gs in...          0
1  price lumber lb f sinc hit ytd high maci turna...          0
2                            say american dream dead         -1
3  barri silbert extrem optimist bitcoin predict ...          1
4  satellit avoid attack space junk circl earth paid         -1

In [6]:
raw_df.columns

Index(['id', 'text', 'timestamp', 'source', 'symbols', 'company_names', 'url',
       'verified'],
      dtype='object')

In [7]:
label_df['sentiment'].value_counts()

sentiment
 0    17330
 1     8512
-1     2598
Name: count, dtype: int64